export const products = [
  {
    id: 1,
    title: "Remera negra",
    price: 15000,
    stock: 2,
    description: "Estas son las mejores zapatillas",
    category: "deportivas",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669326932/free-metcon-4-zapatillas-de-entrenamiento-TQMCZg_fvia3m.png",
  },
  {
    id: 2,
    title: "wilson advance",
    price: 14500,
    stock: 5,
    description: "Ultra livianas y cuentan con camara de aire",
    category: "deportivas",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669430010/foc364fsakkzmausrovn.jpg",
  },
  {
    id: 4,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "urbanas",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669430220/rtokwmt3j03bblbfhwhb.jpg",
  },
  {
    id: 5,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "urbanas",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669430220/rtokwmt3j03bblbfhwhb.jpg",
  },
  {
    id: 6,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "urbanas",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669430220/rtokwmt3j03bblbfhwhb.jpg",
  },
  {
    id: 7,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "urbanas",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669430220/rtokwmt3j03bblbfhwhb.jpg",
  },
  {
    id: 8,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "urbanas",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669430220/rtokwmt3j03bblbfhwhb.jpg",
  },
  {
    id: 9,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "urbanas",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669430220/rtokwmt3j03bblbfhwhb.jpg",
  },
  {
    id: 10,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "urbanas",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669430220/rtokwmt3j03bblbfhwhb.jpg",
  },
]
