export const pokemonList = [
  {
    pokedexN: 12,
    title: "Butterfree",
    type: ["bicho", "volador"],
    description:
      "Butterfree tiene una habilidad especial para encontrar delicioso polen en las flores. Puede localizar, extraer y transportar polen de flores que estén floreciendo a 10 km de distancia de su nido.",
    price: 17000,
    stock: 14,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/012.png",
    stats: {
      hp: 60,
      attack: 45,
      defense: 50,
      "special-attack": 90,
      "special-defense": 80,
      speed: 70,
    },
  },
  {
    pokedexN: 113,
    title: "Chansey",
    type: ["normal"],
    description:
      "Chansey pone a diario huevos con un valor nutritivo altísimo. Están tan ricos que hasta quien no tenga hambre se los comerá en un abrir y cerrar de ojos.",
    price: 20000,
    stock: 17,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/113.png",
    stats: {
      hp: 250,
      attack: 5,
      defense: 5,
      "special-attack": 35,
      "special-defense": 105,
      speed: 50,
    },
  },
  {
    pokedexN: 212,
    title: "Scizor",
    type: ["bicho", "acero"],
    description:
      "Scizor tiene un cuerpo duro como el acero que no es fácil de alterar con ningún ataque común. Este Pokémon bate las alas para regular la temperatura corporal.",
    price: 22000,
    stock: 19,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/212.png",
    stats: {
      hp: 70,
      attack: 130,
      defense: 100,
      "special-attack": 55,
      "special-defense": 80,
      speed: 65,
    },
  },
  {
    pokedexN: 596,
    title: "Galvantula",
    type: ["bicho", "electrico"],
    description:
      "Pone trampas con hilos electrificados. De este modo, electrocuta a sus enemigos y los inmoviliza por completo.",
    price: 21000,
    stock: 17,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/596.png",
    stats: {
      hp: 70,
      attack: 77,
      defense: 60,
      "special-attack": 97,
      "special-defense": 60,
      speed: 108,
    },
  },
  {
    pokedexN: 637,
    title: "Volcarona",
    type: ["bicho", "fuego"],
    description:
      "Cuando combate, despide escamas ardientes de sus seis alas y genera un mar ígneo a su alrededor.",
    price: 24000,
    stock: 15,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/637.png",
    stats: {
      hp: 85,
      attack: 60,
      defense: 65,
      "special-attack": 135,
      "special-defense": 105,
      speed: 100,
    },
  },
  {
    pokedexN: 794,
    title: "Buzzwole",
    type: ["bicho", "lucha"],
    description: "Descripción no disponible para este Pokémon",
    price: 25000,
    stock: 13,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/794.png",
    stats: {
      hp: 107,
      attack: 139,
      defense: 139,
      "special-attack": 53,
      "special-defense": 53,
      speed: 79,
    },
  },
  {
    pokedexN: 149,
    title: "Dragonite",
    type: ["dragon", "volador"],
    description:
      "Dragonite es capaz de dar la vuelta al mundo en solo 16 horas. Es un Pokémon de buen corazón que guía hasta tierra a los barcos que se encuentran perdidos en plena tormenta y a punto de zozobrar.",
    price: 27000,
    stock: 16,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/149.png",
    stats: {
      hp: 91,
      attack: 134,
      defense: 95,
      "special-attack": 100,
      "special-defense": 100,
      speed: 80,
    },
  },
  {
    pokedexN: 334,
    title: "Altaria",
    type: ["dragon", "volador"],
    description:
      "Altaria baila y revolotea por el cielo entre ondeantes nubes que parecen de algodón. Al entonar melodías con su voz cristalina, este Pokémon deja a sus oyentes embobados y admirados.",
    price: 22000,
    stock: 5,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/334.png",
    stats: {
      hp: 75,
      attack: 70,
      defense: 90,
      "special-attack": 70,
      "special-defense": 105,
      speed: 80,
    },
  },
  {
    pokedexN: 380,
    title: "Latias",
    type: ["dragon", "psiquico"],
    description:
      "Latias es muy sensible a los sentimientos de la gente. Si detecta algún ápice de hostilidad, desplegará las plumas que tiene por todo el cuerpo y se pondrá a chillar para intimidar al enemigo.",
    price: 27000,
    stock: 1,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/380.png",
    stats: {
      hp: 80,
      attack: 80,
      defense: 90,
      "special-attack": 110,
      "special-defense": 130,
      speed: 110,
    },
  },
  {
    pokedexN: 381,
    title: "Latios",
    type: ["dragon", "psiquico"],
    description:
      "Latios tiene la habilidad de hacer que los demás vean algo que él ha visto o imaginado. Este Pokémon es muy inteligente. Es capaz de entender el lenguaje humano.",
    price: 27000,
    stock: 1,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/381.png",
    stats: {
      hp: 80,
      attack: 90,
      defense: 80,
      "special-attack": 130,
      "special-defense": 110,
      speed: 110,
    },
  },
  {
    pokedexN: 697,
    title: "Tyrantrum",
    type: ["roca", "dragon"],
    description:
      "En el mundo antiguo en el que habitaba no tenía rivales gracias a sus mandíbulas, con las que podría despedazar con facilidad gruesas placas de acero.",
    price: 23000,
    stock: 10,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/697.png",
    stats: {
      hp: 82,
      attack: 121,
      defense: 119,
      "special-attack": 69,
      "special-defense": 59,
      speed: 71,
    },
  },
  {
    pokedexN: 887,
    title: "Dragapult",
    type: ["dragon", "fantasma"],
    description: "Descripción no disponible para este Pokémon",
    price: 27000,
    stock: 17,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/887.png",
    stats: {
      hp: 88,
      attack: 120,
      defense: 75,
      "special-attack": 100,
      "special-defense": 75,
      speed: 142,
    },
  },
  {
    pokedexN: 36,
    title: "Clefable",
    type: ["hada"],
    description:
      "Clefable se mueve dando saltitos como si fuera haciendo uso de las alas. Estos pequeños brincos le permiten caminar por el agua. De todos es sabido que le encanta darse paseos por los lagos en tranquilas noches de luna llena.",
    price: 21000,
    stock: 12,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/036.png",
    stats: {
      hp: 95,
      attack: 70,
      defense: 73,
      "special-attack": 95,
      "special-defense": 90,
      speed: 60,
    },
  },
  {
    pokedexN: 282,
    title: "Gardevoir",
    type: ["psiquico", "hada"],
    description:
      "Gardevoir es capaz de leer el futuro. Si siente que su Entrenador está en peligro inminente, dicen que libera automáticamente toda su energía psicoquinética.",
    price: 23000,
    stock: 8,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/282.png",
    stats: {
      hp: 68,
      attack: 65,
      defense: 65,
      "special-attack": 125,
      "special-defense": 115,
      speed: 80,
    },
  },
  {
    pokedexN: 730,
    title: "Primarina",
    type: ["agua", "hada"],
    description: "Descripción no disponible para este Pokémon",
    price: 23000,
    stock: 14,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/730.png",
    stats: {
      hp: 80,
      attack: 74,
      defense: 74,
      "special-attack": 126,
      "special-defense": 116,
      speed: 60,
    },
  },
  {
    pokedexN: 778,
    title: "Mimikyu",
    type: ["fantasma", "hada"],
    description: "Descripción no disponible para este Pokémon",
    price: 21000,
    stock: 10,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/778.png",
    stats: {
      hp: 55,
      attack: 90,
      defense: 80,
      "special-attack": 50,
      "special-defense": 105,
      speed: 96,
    },
  },
  {
    pokedexN: 547,
    title: "Whimsicott",
    type: ["planta", "hada"],
    description:
      "Aparecen en medio de un torbellino y entran en las casas para descolocar los muebles o esparcir algodón por doquier.",
    price: 21000,
    stock: 17,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/547.png",
    stats: {
      hp: 60,
      attack: 67,
      defense: 85,
      "special-attack": 77,
      "special-defense": 75,
      speed: 116,
    },
  },
  {
    pokedexN: 6,
    title: "Charizard",
    type: ["fuego", "volador"],
    description:
      "Charizard se dedica a volar por los cielos en busca de oponentes fuertes. Echa fuego por la boca y es capaz de derretir cualquier cosa. No obstante, si su rival es más débil que él, no usará este ataque.",
    price: 24000,
    stock: 18,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/006.png",
    stats: {
      hp: 78,
      attack: 84,
      defense: 78,
      "special-attack": 109,
      "special-defense": 85,
      speed: 100,
    },
  },
  {
    pokedexN: 59,
    title: "Arcanine",
    type: ["fuego"],
    description:
      "Arcanine es conocido por lo veloz que es. Dicen que es capaz de correr 10 000 km en 24 horas. El fuego que arde con vigor en el interior de este Pokémon constituye su fuente de energía.",
    price: 24000,
    stock: 7,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/059.png",
    stats: {
      hp: 90,
      attack: 110,
      defense: 80,
      "special-attack": 100,
      "special-defense": 80,
      speed: 95,
    },
  },
  {
    pokedexN: 136,
    title: "Flareon",
    type: ["fuego"],
    description:
      "La suavidad del pelaje de Flareon tiene una función clara: libera calor para que el Pokémon no se asfixie. La temperatura corporal de este Pokémon puede alcanzar los 900 °C.",
    price: 23000,
    stock: 9,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/136.png",
    stats: {
      hp: 65,
      attack: 130,
      defense: 60,
      "special-attack": 95,
      "special-defense": 110,
      speed: 65,
    },
  },
  {
    pokedexN: 229,
    title: "Houndoom",
    type: ["siniestro", "fuego"],
    description:
      "En la manada de Houndoom, el que tiene los cuernos más arqueados hacia atrás tiene un mayor papel de liderazgo. Estos Pokémon suelen elegir al jefe en duelo.",
    price: 22000,
    stock: 13,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/229.png",
    stats: {
      hp: 75,
      attack: 90,
      defense: 50,
      "special-attack": 110,
      "special-defense": 80,
      speed: 95,
    },
  },
  {
    pokedexN: 250,
    title: "Ho-oh",
    type: ["fuego", "volador"],
    description:
      "El plumaje de Ho-Oh contiene siete colores que pueden apreciarse según el ángulo desde el que les dé la luz. Dicen que sus plumas dan felicidad a quienes las llevan y, también, que este Pokémon vive a los pies del arco iris.",
    price: 30000,
    stock: 1,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/250.png",
    stats: {
      hp: 106,
      attack: 130,
      defense: 90,
      "special-attack": 110,
      "special-defense": 154,
      speed: 90,
    },
  },
  {
    pokedexN: 257,
    title: "Blaziken",
    type: ["fuego", "lucha"],
    description:
      "En combate, Blaziken expulsa vivas llamas por las muñecas y ataca al enemigo con fiereza. Cuanto más fuerte sea el enemigo, más intensas serán las llamas.",
    price: 23000,
    stock: 13,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/257.png",
    stats: {
      hp: 80,
      attack: 120,
      defense: 70,
      "special-attack": 110,
      "special-defense": 70,
      speed: 80,
    },
  },
  {
    pokedexN: 392,
    title: "Infernape",
    type: ["fuego", "lucha"],
    description:
      "Su corona de fuego demuestra su naturaleza ígnea. Nadie le gana en velocidad.",
    price: 24000,
    stock: 14,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/392.png",
    stats: {
      hp: 76,
      attack: 104,
      defense: 71,
      "special-attack": 104,
      "special-defense": 71,
      speed: 108,
    },
  },
  {
    pokedexN: 609,
    title: "Chandelure",
    type: ["fantasma", "fuego"],
    description:
      "Sus llamas absorben el alma del enemigo y la abrasan, dejando solo su cuerpo inerte.",
    price: 23000,
    stock: 12,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/609.png",
    stats: {
      hp: 60,
      attack: 55,
      defense: 90,
      "special-attack": 145,
      "special-defense": 90,
      speed: 80,
    },
  },
  {
    pokedexN: 663,
    title: "Talonflame",
    type: ["fuego", "volador"],
    description:
      "Si se exalta durante un combate reñido, arroja chispas y ascuas de los intersticios entre su plumaje mientras vuela.",
    price: 22000,
    stock: 15,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/663.png",
    stats: {
      hp: 78,
      attack: 81,
      defense: 71,
      "special-attack": 74,
      "special-defense": 69,
      speed: 126,
    },
  },
  {
    pokedexN: 146,
    title: "Moltres",
    type: ["fuego", "volador"],
    description:
      "Moltres es un Pokémon pájaro legendario que tiene la habilidad de controlar el fuego. Dicen que, si resulta herido, se sumerge en el líquido magma de un volcán para arder y curarse.",
    price: 26000,
    stock: 1,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/146.png",
    stats: {
      hp: 90,
      attack: 100,
      defense: 90,
      "special-attack": 125,
      "special-defense": 85,
      speed: 90,
    },
  },
  {
    pokedexN: 94,
    title: "Gengar",
    type: ["fantasma", "veneno"],
    description:
      "Si alguien ve que su sombra le adelanta de repente en una noche oscura, es muy probable que lo que esté viendo no sea su sombra, sino a un Gengar haciéndose pasar por la misma.",
    price: 22000,
    stock: 11,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/094.png",
    stats: {
      hp: 60,
      attack: 65,
      defense: 60,
      "special-attack": 130,
      "special-defense": 75,
      speed: 110,
    },
  },
  {
    pokedexN: 442,
    title: "Spiritomb",
    type: ["fantasma", "siniestro"],
    description:
      "Se formó a partir de 108 espíritus. Está unido a la fisura de una piedra angular mística.",
    price: 21000,
    stock: 12,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/442.png",
    stats: {
      hp: 50,
      attack: 92,
      defense: 108,
      "special-attack": 92,
      "special-defense": 108,
      speed: 35,
    },
  },
  {
    pokedexN: 681,
    title: "Aegislash",
    type: ["acero", "fantasma"],
    description:
      "Han permanecido junto a estirpes de reyes durante generaciones. Mediante su poder espectral pueden controlar a humanos y a Pokémon.",
    price: 22000,
    stock: 9,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/681.png",
    stats: {
      hp: 60,
      attack: 50,
      defense: 140,
      "special-attack": 50,
      "special-defense": 140,
      speed: 60,
    },
  },
  {
    pokedexN: 724,
    title: "Decidueye",
    type: ["planta", "fantasma"],
    description: "Descripción no disponible para este Pokémon",
    price: 23000,
    stock: 17,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/724.png",
    stats: {
      hp: 78,
      attack: 107,
      defense: 75,
      "special-attack": 100,
      "special-defense": 100,
      speed: 70,
    },
  },
  {
    pokedexN: 31,
    title: "Nidoqueen",
    type: ["veneno", "tierra"],
    description:
      "Nidoqueen tiene el cuerpo totalmente recubierto de escamas durísimas. Suele lanzar por los aires a sus rivales de los violentos golpes que les propina. Cuando se trata de defender a sus crías, alcanza su nivel máximo de fuerza.",
    price: 22000,
    stock: 6,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/031.png",
    stats: {
      hp: 90,
      attack: 92,
      defense: 87,
      "special-attack": 75,
      "special-defense": 85,
      speed: 76,
    },
  },
  {
    pokedexN: 34,
    title: "Nidoking",
    type: ["veneno", "tierra"],
    description:
      "La gruesa cola de Nidoking encierra una fuerza realmente destructora. Con una vez que la agite, es capaz de tumbar una torre metálica de transmisión. Una vez que este Pokémon se desboca, no hay quien lo pare.",
    price: 22000,
    stock: 18,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/034.png",
    stats: {
      hp: 81,
      attack: 102,
      defense: 77,
      "special-attack": 85,
      "special-defense": 75,
      speed: 85,
    },
  },
  {
    pokedexN: 208,
    title: "Steelix",
    type: ["acero", "tierra"],
    description:
      "Steelix vive a mayor profundidad aún que Onix. Se le conoce por su tendencia a excavar hacia el interior del planeta. Hay datos que muestran que este Pokémon ha llegado a alcanzar 1 km de profundidad.",
    price: 22000,
    stock: 8,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/208.png",
    stats: {
      hp: 75,
      attack: 85,
      defense: 200,
      "special-attack": 55,
      "special-defense": 65,
      speed: 30,
    },
  },
  {
    pokedexN: 260,
    title: "Swampert",
    type: ["agua", "tierra"],
    description:
      "Swampert es muy fuerte. Puede arrastrar una roca que pese más de una tonelada sin ningún problema. Este Pokémon tiene el sentido de la vista muy desarrollado. Es capaz de ver hasta en aguas cenagosas.",
    price: 24000,
    stock: 9,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/260.png",
    stats: {
      hp: 100,
      attack: 110,
      defense: 90,
      "special-attack": 85,
      "special-defense": 90,
      speed: 60,
    },
  },
  {
    pokedexN: 383,
    title: "Groudon",
    type: ["tierra"],
    description:
      "A Groudon siempre se le ha descrito como el Pokémon que expandió los continentes. Varias leyendas cuentan que libró combates contra Kyogre en repetidas ocasiones para tener el control de la energía de la naturaleza.",
    price: 30000,
    stock: 1,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/383.png",
    stats: {
      hp: 100,
      attack: 150,
      defense: 140,
      "special-attack": 100,
      "special-defense": 90,
      speed: 90,
    },
  },
  {
    pokedexN: 445,
    title: "Garchomp",
    type: ["dragon", "tierra"],
    description:
      "Cuando despliega su cuerpo y sus alas, parece un avión a reacción. Vuela a velocidad sónica.",
    price: 27000,
    stock: 13,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/445.png",
    stats: {
      hp: 108,
      attack: 130,
      defense: 95,
      "special-attack": 80,
      "special-defense": 85,
      speed: 102,
    },
  },
  {
    pokedexN: 133,
    title: "Eevee",
    type: ["normal"],
    description:
      "La configuración genética de Eevee le permite mutar y adaptarse enseguida a cualquier medio en el que viva. La evolución de este Pokémon suele ser posible gracias a las radiaciones emitidas por varias piedras.",
    price: 14000,
    stock: 7,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/133.png",
    stats: {
      hp: 55,
      attack: 55,
      defense: 50,
      "special-attack": 45,
      "special-defense": 65,
      speed: 55,
    },
  },
  {
    pokedexN: 143,
    title: "Snorlax",
    type: ["normal"],
    description:
      "Un día cualquiera en la vida de Snorlax consiste en comer y dormir. Es un Pokémon tan dócil que es fácil ver niños usando la gran panza que tiene como lugar de juegos.",
    price: 24000,
    stock: 6,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/143.png",
    stats: {
      hp: 160,
      attack: 110,
      defense: 65,
      "special-attack": 65,
      "special-defense": 110,
      speed: 30,
    },
  },
  {
    pokedexN: 398,
    title: "Staraptor",
    type: ["normal", "volador"],
    description:
      "Sus alas y sus patas son muy fuertes. Puede llevarse volando Pokémon pequeños.",
    price: 21000,
    stock: 15,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/398.png",
    stats: {
      hp: 85,
      attack: 120,
      defense: 70,
      "special-attack": 50,
      "special-defense": 60,
      speed: 100,
    },
  },
  {
    pokedexN: 760,
    title: "Bewear",
    type: ["normal", "lucha"],
    description: "Descripción no disponible para este Pokémon",
    price: 22000,
    stock: 18,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/760.png",
    stats: {
      hp: 120,
      attack: 125,
      defense: 80,
      "special-attack": 55,
      "special-defense": 60,
      speed: 60,
    },
  },
  {
    pokedexN: 65,
    title: "Alakazam",
    type: ["psiquico"],
    description:
      "El cerebro de Alakazam nunca deja de crecer y por eso al cuello le cuesta sostener el peso de la cabeza. Este Pokémon usa sus poderes psicoquinéticos para mantener en alto la cabeza.",
    price: 22000,
    stock: 16,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/065.png",
    stats: {
      hp: 55,
      attack: 50,
      defense: 45,
      "special-attack": 135,
      "special-defense": 95,
      speed: 120,
    },
  },
  {
    pokedexN: 306,
    title: "Aggron",
    type: ["acero", "roca"],
    description:
      "Aggron marca una montaña entera como su territorio y acaba con todo lo que pueda ponerlo en peligro. Este Pokémon está continuamente patrullando la zona en defensa de su terreno.",
    price: 23000,
    stock: 7,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/306.png",
    stats: {
      hp: 70,
      attack: 110,
      defense: 180,
      "special-attack": 60,
      "special-defense": 60,
      speed: 50,
    },
  },
  {
    pokedexN: 395,
    title: "Empoleon",
    type: ["agua", "acero"],
    description:
      "Nada tan rápido como un fueraborda. Con los afilados bordes de sus alas puede cortar el hielo.",
    price: 23000,
    stock: 9,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/395.png",
    stats: {
      hp: 84,
      attack: 86,
      defense: 88,
      "special-attack": 111,
      "special-defense": 101,
      speed: 60,
    },
  },
  {
    pokedexN: 625,
    title: "Bisharp",
    type: ["siniestro", "acero"],
    description:
      "Un Pokémon temible que remata a su presa una vez que su séquito de Pawniard la ha debilitado e inmovilizado.",
    price: 22000,
    stock: 17,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/625.png",
    stats: {
      hp: 65,
      attack: 125,
      defense: 100,
      "special-attack": 60,
      "special-defense": 70,
      speed: 70,
    },
  },
  {
    pokedexN: 150,
    title: "Mewtwo",
    type: ["psiquico"],
    description:
      "Mewtwo fue creado por manipulación genética. Pero, a pesar de que el hombre creó su cuerpo, dotar a Mewtwo de un corazón compasivo quedó en el olvido.",
    price: 30000,
    stock: 1,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/150.png",
    stats: {
      hp: 106,
      attack: 110,
      defense: 90,
      "special-attack": 154,
      "special-defense": 90,
      speed: 130,
    },
  },
  {
    pokedexN: 197,
    title: "Umbreon",
    type: ["siniestro"],
    description:
      "Umbreon evolucionó tras haber estado expuesto a ondas lunares. Suele esconderse en la oscuridad en silencio y esperar a que su presa se mueva. Cuando se lanza al ataque, le brillan los anillos del cuerpo.",
    price: 23000,
    stock: 15,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/197.png",
    stats: {
      hp: 95,
      attack: 65,
      defense: 110,
      "special-attack": 60,
      "special-defense": 130,
      speed: 65,
    },
  },
  {
    pokedexN: 248,
    title: "Tyranitar",
    type: ["roca", "siniestro"],
    description:
      "Tyranitar tiene una fuerza imponente; es capaz de echar abajo una montaña para hacer su nido. Este Pokémon suele merodear por las zonas de montaña en busca de nuevos rivales contra los que luchar.",
    price: 27000,
    stock: 12,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/248.png",
    stats: {
      hp: 100,
      attack: 134,
      defense: 110,
      "special-attack": 95,
      "special-defense": 100,
      speed: 61,
    },
  },
  {
    pokedexN: 560,
    title: "Scrafty",
    type: ["siniestro", "lucha"],
    description:
      "Se protege de los ataques con la muda de su piel mientras reparte patadas. Cuanto mayor es su cresta, más se le respeta.",
    price: 21000,
    stock: 10,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/560.png",
    stats: {
      hp: 65,
      attack: 90,
      defense: 115,
      "special-attack": 45,
      "special-defense": 115,
      speed: 58,
    },
  },
  {
    pokedexN: 630,
    title: "Mandibuzz",
    type: ["siniestro", "volador"],
    description:
      "Vuela en círculos. Cuando avista una presa, la ataca y la transporta a su nido con suma facilidad.",
    price: 22000,
    stock: 6,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/630.png",
    stats: {
      hp: 110,
      attack: 65,
      defense: 105,
      "special-attack": 55,
      "special-defense": 95,
      speed: 80,
    },
  },
  {
    pokedexN: 658,
    title: "Greninja",
    type: ["agua", "siniestro"],
    description:
      "Comprime el agua y crea estrellas ninja con las que ataca al enemigo. Cuando las hace girar a gran velocidad cortan en dos hasta el metal.",
    price: 23000,
    stock: 10,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/658.png",
    stats: {
      hp: 72,
      attack: 95,
      defense: 67,
      "special-attack": 103,
      "special-defense": 71,
      speed: 122,
    },
  },
  {
    pokedexN: 338,
    title: "Solrock",
    type: ["roca", "psiquico"],
    description:
      "Solrock pertenece a una nueva especie de Pokémon a la que se le atribuye una procedencia extraterrestre. Este Pokémon permanece flotando en el aire y se mueve muy despacio. Al luchar, desprende una luz viva e intensa.",
    price: 20000,
    stock: 17,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/338.png",
    stats: {
      hp: 90,
      attack: 95,
      defense: 85,
      "special-attack": 55,
      "special-defense": 65,
      speed: 70,
    },
  },
  {
    pokedexN: 25,
    title: "Pikachu",
    type: ["electrico"],
    description:
      "Cada vez que un Pikachu se encuentra con algo nuevo, le lanza una descarga eléctrica. Cuando se ve alguna baya chamuscada, es muy probable que sea obra de un Pikachu, ya que a veces no controlan la intensidad de la descarga.",
    price: 14000,
    stock: 8,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/025.png",
    stats: {
      hp: 35,
      attack: 55,
      defense: 40,
      "special-attack": 50,
      "special-defense": 50,
      speed: 90,
    },
  },
  {
    pokedexN: 135,
    title: "Jolteon",
    type: ["electrico"],
    description:
      "Las células de Jolteon generan un nivel bajo de electricidad, cuya intensidad aumenta con la electricidad estática que acumula en un pelaje formado por agujas cargadas de electricidad. Esta característica le permite lanzar rayos.",
    price: 23000,
    stock: 19,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/135.png",
    stats: {
      hp: 65,
      attack: 65,
      defense: 60,
      "special-attack": 110,
      "special-defense": 95,
      speed: 130,
    },
  },
  {
    pokedexN: 311,
    title: "Plusle",
    type: ["electrico"],
    description:
      "Plusle siempre anima a sus compañeros. Cuando algún miembro de su grupo hace un gran esfuerzo en combate, causa un cortocircuito en su interior para mostrar con el chisporroteo su alegría.",
    price: 18000,
    stock: 7,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/311.png",
    stats: {
      hp: 60,
      attack: 50,
      defense: 40,
      "special-attack": 85,
      "special-defense": 75,
      speed: 95,
    },
  },
  {
    pokedexN: 312,
    title: "Minun",
    type: ["electrico"],
    description:
      "Minun se preocupa más por alentar a sus compañeros de equipo que por su propia seguridad. Para animar a los miembros de su grupo, crea un cortocircuito en su interior y libera un chisporroteo espectacular.",
    price: 18000,
    stock: 8,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/312.png",
    stats: {
      hp: 60,
      attack: 40,
      defense: 50,
      "special-attack": 75,
      "special-defense": 85,
      speed: 95,
    },
  },
  {
    pokedexN: 587,
    title: "Emolga",
    type: ["electrico", "volador"],
    description:
      "Vive en la copa de los árboles. Produce descargas mientras vuela con el interior de la membrana que hace de capa.",
    price: 19000,
    stock: 5,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/587.png",
    stats: {
      hp: 55,
      attack: 75,
      defense: 60,
      "special-attack": 75,
      "special-defense": 60,
      speed: 103,
    },
  },
  {
    pokedexN: 807,
    title: "Zeraora",
    type: ["electrico"],
    description: "Descripción no disponible para este Pokémon",
    price: 27000,
    stock: 0,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/807.png",
    stats: {
      hp: 88,
      attack: 112,
      defense: 75,
      "special-attack": 102,
      "special-defense": 80,
      speed: 143,
    },
  },
  {
    pokedexN: 68,
    title: "Machamp",
    type: ["lucha"],
    description:
      "Machamp es tan fuerte que puede derribar lo que quiera. Sin embargo, cuando tiene que realizar una tarea que requiere delicadeza y destreza, se le enredan los brazos. Este Pokémon pasa a la acción sin pensar.",
    price: 22000,
    stock: 6,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/068.png",
    stats: {
      hp: 90,
      attack: 130,
      defense: 80,
      "special-attack": 65,
      "special-defense": 85,
      speed: 55,
    },
  },
  {
    pokedexN: 448,
    title: "Lucario",
    type: ["lucha", "acero"],
    description:
      "Puede leer los pensamientos y movimientos de su adversario a través de su aura.",
    price: 23000,
    stock: 8,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/448.png",
    stats: {
      hp: 70,
      attack: 110,
      defense: 70,
      "special-attack": 115,
      "special-defense": 70,
      speed: 90,
    },
  },
  {
    pokedexN: 534,
    title: "Conkeldurr",
    type: ["lucha"],
    description:
      "Se cree que Conkeldurr enseñó a los humanos la técnica para elaborar cemento hace más de 2000 años.",
    price: 22000,
    stock: 15,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/534.png",
    stats: {
      hp: 105,
      attack: 140,
      defense: 95,
      "special-attack": 55,
      "special-defense": 65,
      speed: 45,
    },
  },
  {
    pokedexN: 701,
    title: "Hawlucha",
    type: ["lucha", "volador"],
    description:
      "A pesar de ser un Pokémon de pequeña estatura, su pericia en el combate le permite plantar cara a Pokémon como Machamp o Hariyama.",
    price: 22000,
    stock: 18,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/701.png",
    stats: {
      hp: 78,
      attack: 92,
      defense: 75,
      "special-attack": 74,
      "special-defense": 63,
      speed: 118,
    },
  },
  {
    pokedexN: 18,
    title: "Pidgeot",
    type: ["normal", "volador"],
    description:
      "El plumaje de este Pokémon es bonito e hipnótico. Muchos Entrenadores se quedan embobados ante la belleza impactante de las plumas que tiene en la cabeza; lo que les lleva a elegir a Pidgeot como su Pokémon.",
    price: 21000,
    stock: 12,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/018.png",
    stats: {
      hp: 83,
      attack: 80,
      defense: 75,
      "special-attack": 70,
      "special-defense": 70,
      speed: 101,
    },
  },
  {
    pokedexN: 130,
    title: "Gyarados",
    type: ["agua", "volador"],
    description:
      "Cuando Magikarp evoluciona y se convierte en Gyarados, sufre un cambio estructural en las células del cerebro. Dicen que esa transformación es la causa de la naturaleza violenta y salvaje de este Pokémon.",
    price: 24000,
    stock: 7,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/130.png",
    stats: {
      hp: 95,
      attack: 125,
      defense: 79,
      "special-attack": 60,
      "special-defense": 100,
      speed: 81,
    },
  },
  {
    pokedexN: 142,
    title: "Aerodactyl",
    type: ["roca", "volador"],
    description:
      "Los orígenes de Aerodactyl datan de la era de los dinosaurios. Se regeneró a partir de material genético contenido en ámbar. Se supone que fue el amo de los cielos en épocas pasadas.",
    price: 23000,
    stock: 7,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/142.png",
    stats: {
      hp: 80,
      attack: 105,
      defense: 65,
      "special-attack": 60,
      "special-defense": 75,
      speed: 130,
    },
  },
  {
    pokedexN: 337,
    title: "Lunatone",
    type: ["roca", "psiquico"],
    description:
      "Lunatone fue descubierto en el lugar de impacto de un meteorito. Por eso, hay quien especula con la idea de que procede del espacio. Con todo, hasta el día de hoy nadie ha podido probar esta teoría.",
    price: 20000,
    stock: 10,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/337.png",
    stats: {
      hp: 90,
      attack: 55,
      defense: 65,
      "special-attack": 95,
      "special-defense": 85,
      speed: 70,
    },
  },
  {
    pokedexN: 144,
    title: "Articuno",
    type: ["hielo", "volador"],
    description:
      "Articuno es un Pokémon pájaro legendario que puede controlar el hielo. El batir de sus alas congela el aire. Dicen que consigue hacer que nieve cuando vuela.",
    price: 26000,
    stock: 1,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/144.png",
    stats: {
      hp: 90,
      attack: 85,
      defense: 100,
      "special-attack": 95,
      "special-defense": 125,
      speed: 85,
    },
  },
  {
    pokedexN: 145,
    title: "Zapdos",
    type: ["electrico", "volador"],
    description:
      "Zapdos es un Pokémon pájaro legendario que tiene la habilidad de controlar la electricidad. Suele vivir en nubarrones. Este Pokémon gana mucha fuerza si le alcanzan los rayos.",
    price: 26000,
    stock: 1,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/145.png",
    stats: {
      hp: 90,
      attack: 90,
      defense: 85,
      "special-attack": 125,
      "special-defense": 90,
      speed: 100,
    },
  },
  {
    pokedexN: 3,
    title: "Venusaur",
    type: ["planta", "veneno"],
    description:
      "Venusaur tiene una flor enorme en el lomo que, según parece, adquiere unos colores muy vivos si está bien nutrido y le da mucho el sol. El aroma delicado de la flor tiene un efecto relajante en el ánimo de las personas.",
    price: 23000,
    stock: 14,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/003.png",
    stats: {
      hp: 80,
      attack: 82,
      defense: 83,
      "special-attack": 100,
      "special-defense": 100,
      speed: 80,
    },
  },
  {
    pokedexN: 152,
    title: "Chikorita",
    type: ["planta"],
    description:
      "Al luchar, Chikorita agita la hoja que tiene para mantener a raya al rival. Pero, al mismo tiempo, libera una suave fragancia que apacigua el encuentro y crea un ambiente agradable y de amistad.",
    price: 14000,
    stock: 10,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/152.png",
    stats: {
      hp: 45,
      attack: 49,
      defense: 65,
      "special-attack": 49,
      "special-defense": 65,
      speed: 45,
    },
  },
  {
    pokedexN: 385,
    title: "Jirachi",
    type: ["acero", "psiquico"],
    description:
      "Cuenta la leyenda que Jirachi hará realidad cualquier deseo que se le escriba en las notas que lleva en la cabeza cuando las lea tras salir de su letargo. Si este Pokémon siente peligro, luchará sin haber llegado a despertarse.",
    price: 27000,
    stock: 1,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/385.png",
    stats: {
      hp: 100,
      attack: 100,
      defense: 100,
      "special-attack": 100,
      "special-defense": 100,
      speed: 100,
    },
  },
  {
    pokedexN: 475,
    title: "Gallade",
    type: ["psiquico", "lucha"],
    description:
      "Puede presentir los movimientos de sus rivales y por eso ataca siempre antes que ellos.",
    price: 23000,
    stock: 18,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/475.png",
    stats: {
      hp: 68,
      attack: 125,
      defense: 65,
      "special-attack": 65,
      "special-defense": 115,
      speed: 80,
    },
  },
  {
    pokedexN: 227,
    title: "Skarmory",
    type: ["acero", "volador"],
    description:
      "Skarmory está totalmente encerrado en el interior de una fuerte coraza protectora. En vuelo, puede llegar a alcanzar los 300 km/h y usa las afiladas alas que tiene para azotar al rival.",
    price: 20000,
    stock: 19,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/227.png",
    stats: {
      hp: 65,
      attack: 80,
      defense: 140,
      "special-attack": 40,
      "special-defense": 70,
      speed: 70,
    },
  },
  {
    pokedexN: 151,
    title: "Mew",
    type: ["psiquico"],
    description:
      "Dicen que Mew posee el mapa genético de todos los Pokémon. Puede hacerse invisible cuando quiere, así que pasa desapercibido cada vez que se le acerca alguien.",
    price: 27000,
    stock: 1,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/151.png",
    stats: {
      hp: 100,
      attack: 100,
      defense: 100,
      "special-attack": 100,
      "special-defense": 100,
      speed: 100,
    },
  },
  {
    pokedexN: 470,
    title: "Leafeon",
    type: ["planta"],
    description:
      "En días soleados duerme y hace la fotosíntesis, emitiendo aire puro a su alrededor.",
    price: 23000,
    stock: 15,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/470.png",
    stats: {
      hp: 65,
      attack: 110,
      defense: 130,
      "special-attack": 60,
      "special-defense": 65,
      speed: 95,
    },
  },
  {
    pokedexN: 497,
    title: "Serperior",
    type: ["planta"],
    description:
      "Tan solo muestra su verdadero poder a quienes no se amedrentan ante su noble pero inquisitoria mirada.",
    price: 23000,
    stock: 11,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/497.png",
    stats: {
      hp: 75,
      attack: 75,
      defense: 95,
      "special-attack": 75,
      "special-defense": 95,
      speed: 113,
    },
  },
  {
    pokedexN: 586,
    title: "Sawsbuck",
    type: ["normal", "planta"],
    description:
      "Cambia de morada dependiendo de las estaciones. Observando sus cuernos, la gente sabe cuándo estas van a cambiar.",
    price: 21000,
    stock: 14,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/586.png",
    stats: {
      hp: 80,
      attack: 100,
      defense: 70,
      "special-attack": 60,
      "special-defense": 70,
      speed: 95,
    },
  },
  {
    pokedexN: 131,
    title: "Lapras",
    type: ["agua", "hielo"],
    description:
      "Por culpa de la gente, Lapras está casi en extinción. Dicen que, al anochecer, se pone a cantar quejicoso mientras busca a los miembros de su especie que puedan quedar.",
    price: 24000,
    stock: 16,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/131.png",
    stats: {
      hp: 130,
      attack: 85,
      defense: 80,
      "special-attack": 85,
      "special-defense": 95,
      speed: 60,
    },
  },
  {
    pokedexN: 238,
    title: "Smoochum",
    type: ["hielo", "psiquico"],
    description:
      "Smoochum va corriendo por todos lados, pero se cae también con frecuencia. Y, en cuanto tiene ocasión, se mira en algún sitio para ver si se ha manchado la cara.",
    price: 13000,
    stock: 9,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/238.png",
    stats: {
      hp: 45,
      attack: 30,
      defense: 15,
      "special-attack": 85,
      "special-defense": 65,
      speed: 65,
    },
  },
  {
    pokedexN: 471,
    title: "Glaceon",
    type: ["hielo"],
    description:
      "Controla su temperatura corporal para congelar el ambiente y causar ráfagas de nieve en polvo.",
    price: 23000,
    stock: 18,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/471.png",
    stats: {
      hp: 65,
      attack: 60,
      defense: 110,
      "special-attack": 130,
      "special-defense": 95,
      speed: 65,
    },
  },
  {
    pokedexN: 73,
    title: "Tentacruel",
    type: ["agua", "veneno"],
    description:
      "Tentacruel tiene unas enormes esferas rojas en la cabeza, que brillan antes de lanzar una descarga ultrasónica a lo que le rodea. Este estallido crea unas olas tremendas a su alrededor.",
    price: 23000,
    stock: 16,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/073.png",
    stats: {
      hp: 80,
      attack: 70,
      defense: 65,
      "special-attack": 80,
      "special-defense": 120,
      speed: 100,
    },
  },
  {
    pokedexN: 317,
    title: "Swalot",
    type: ["veneno"],
    description:
      "Cuando Swalot detecta una presa, echa por los poros, y a borbotones, un fluido tóxico espantoso con el que rocía a su víctima. Una vez que la debilita, se la traga entera gracias a la gigantesca boca que tiene.",
    price: 21000,
    stock: 18,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/317.png",
    stats: {
      hp: 100,
      attack: 73,
      defense: 83,
      "special-attack": 73,
      "special-defense": 83,
      speed: 55,
    },
  },
  {
    pokedexN: 185,
    title: "Sudowoodo",
    type: ["roca"],
    description:
      "Sudowoodo se camufla adoptando la imagen de un árbol para que no le ataque ningún enemigo. El problema viene en invierno, ya que las extremidades superiores tienen color verde y es fácil identificarle.",
    price: 18000,
    stock: 12,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/185.png",
    stats: {
      hp: 70,
      attack: 100,
      defense: 115,
      "special-attack": 30,
      "special-defense": 65,
      speed: 30,
    },
  },
  {
    pokedexN: 409,
    title: "Rampardos",
    type: ["roca"],
    description:
      "Tiene sesos pequeños porque su duro cráneo, que soporta cualquier golpe, les impide desarrollarse.",
    price: 22000,
    stock: 5,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/409.png",
    stats: {
      hp: 97,
      attack: 165,
      defense: 60,
      "special-attack": 65,
      "special-defense": 50,
      speed: 58,
    },
  },
  {
    pokedexN: 558,
    title: "Crustle",
    type: ["bicho", "roca"],
    description:
      "Su inmensa capacidad motriz le permite desplazarse cargando a sus espaldas rocas enormes durante días.",
    price: 21000,
    stock: 16,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/558.png",
    stats: {
      hp: 70,
      attack: 105,
      defense: 125,
      "special-attack": 65,
      "special-defense": 75,
      speed: 45,
    },
  },
  {
    pokedexN: 9,
    title: "Blastoise",
    type: ["agua"],
    description:
      "Blastoise lanza chorros de agua con gran precisión por los tubos que le salen del caparazón que tiene en la espalda. Puede disparar chorros de agua con tanta puntería que no fallaría al tirar contra una lata pequeña a 50 m.",
    price: 23000,
    stock: 16,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/009.png",
    stats: {
      hp: 79,
      attack: 83,
      defense: 100,
      "special-attack": 85,
      "special-defense": 105,
      speed: 78,
    },
  },
  {
    pokedexN: 121,
    title: "Starmie",
    type: ["agua", "psiquico"],
    description:
      "La parte central de Starmie, el núcleo brillante, resplandece con siete colores distintos. Debido a su naturaleza luminosa, a este Pokémon se le ha dado el apelativo de la Gema del Mar.",
    price: 23000,
    stock: 15,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/121.png",
    stats: {
      hp: 60,
      attack: 75,
      defense: 85,
      "special-attack": 100,
      "special-defense": 85,
      speed: 115,
    },
  },
  {
    pokedexN: 134,
    title: "Vaporeon",
    type: ["agua"],
    description:
      "Vaporeon sufrió una mutación repentina y desarrolló aletas y branquias que le permiten vivir bajo el agua. Asimismo, este Pokémon tiene la habilidad de controlar las aguas.",
    price: 23000,
    stock: 12,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/134.png",
    stats: {
      hp: 130,
      attack: 65,
      defense: 60,
      "special-attack": 110,
      "special-defense": 95,
      speed: 65,
    },
  },
  {
    pokedexN: 350,
    title: "Milotic",
    type: ["agua"],
    description:
      "De Milotic se dice que es el Pokémon más bello. Tiene la capacidad de calmar sentimientos tales como el miedo y la hostilidad, y apaciguar las relaciones de áspera enemistad.",
    price: 24000,
    stock: 12,
    img: "https:/assets.pokemon.com/assets/cms2/img/pokedex/full/350.png",
    stats: {
      hp: 95,
      attack: 60,
      defense: 79,
      "special-attack": 100,
      "special-defense": 125,
      speed: 81,
    },
  },
]
